### ISSUE TITLE
Implement the LemonVM IR

### ISSUE THREAD

**Issue by LemonHX** [LemonVM/LemonVM-IR-Spec#1]
# LemonVM IR

LemonVM IR 是一层AST旨在将人类可读的AST转换成相应的VM字节码
后期可能准备做多语言协作

需要遵循
- S表达式 `(add @3 @1 @2)`
- 区分不同类型的寄存器
- 建立一部分数据的抽象比如Row Type

**Comment by imkiva** [comment]
I suggest we can put all docs in this repo

**Comment by LemonHX** [comment]
docs should be in particular project, or another repo for general docs
